//
// ModelErrorResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@objc public class ModelErrorResponse: NSObject, Codable, JSONEncodable {

    /** Status code for Http Request */
    public var status: Int
    /** Error message */
    public var errorMessage: String
    /** Message code for Error */
    public var messageCode: String

    public init(status: Int, errorMessage: String, messageCode: String) {
        self.status = status
        self.errorMessage = errorMessage
        self.messageCode = messageCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case errorMessage = "error_message"
        case messageCode = "message_code"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(errorMessage, forKey: .errorMessage)
        try container.encode(messageCode, forKey: .messageCode)
    }
}

