//
// PostSubscriptionOrganizationModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Request body for subscription creation. */
public struct PostSubscriptionOrganizationModel: Codable, JSONEncodable, Hashable {

    public enum EnvironmentOrganizationModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case sandbox = "sandbox"
        case production = "production"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public enum TypeOrganizationModel: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case webhook = "webhook"
        case email = "email"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    /** The environment that the subscription is configured for. */
    public var environment: EnvironmentOrganizationModel
    /** Type of the subscription. */
    public var type: TypeOrganizationModel
    /** Name provided for the subscription. */
    public var name: String
    /** URL provided for the subscription. Required when type is webhook. */
    public var url: String?
    /** Recipient email address. Required when type is email. */
    public var recipient: String?

    public init(environment: EnvironmentOrganizationModel, type: TypeOrganizationModel, name: String, url: String? = nil, recipient: String? = nil) {
        self.environment = environment
        self.type = type
        self.name = name
        self.url = url
        self.recipient = recipient
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case environment
        case type
        case name
        case url
        case recipient
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(environment, forKey: .environment)
        try container.encode(type, forKey: .type)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(recipient, forKey: .recipient)
    }
}

