//
// PostSubscriptionDeliveryOrganizationModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Request body for subscription delivery creation. */
public struct PostSubscriptionDeliveryOrganizationModel: Codable, JSONEncodable, Hashable {

    /** The event guid . */
    public var subscriptionEventGuid: String
    /** The subscription guid. */
    public var subscriptionGuid: String

    public init(subscriptionEventGuid: String, subscriptionGuid: String) {
        self.subscriptionEventGuid = subscriptionEventGuid
        self.subscriptionGuid = subscriptionGuid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case subscriptionEventGuid = "subscription_event_guid"
        case subscriptionGuid = "subscription_guid"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(subscriptionEventGuid, forKey: .subscriptionEventGuid)
        try container.encode(subscriptionGuid, forKey: .subscriptionGuid)
    }
}

