//
// SubscriptionType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum SubscriptionType: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case webhook = "webhook"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
