//
// SubscriptionEnvironment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum SubscriptionEnvironment: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case sandbox = "sandbox"
    case production = "production"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
