name: CybridApiOrganizationSwift
targets:
  CybridApiOrganizationSwift:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [CybridApiOrganizationSwift/APIClient]
    info:
      path: ./Info.plist
      version: 0.38.3
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
